imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enable: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
  encoders:
      Symfony\Component\Security\Core\User\User: plaintext

  firewalls:
      main:
          http_basic: true

# Doctrine Configuration
doctrine:
    dbal:
        dbname:   %database_name%_test
