imports:
    - { resource: parameters.php }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    session:         ~
    router_proxy:   { path: /_proxy }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "EntvalleyAppBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        less: ~
        lessphp:
            apply_to: "\.less$"
            file:   %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%

        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
        type: file
        path: "%kernel.root_dir%/mail"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Entvalley\AppBundle\Entity\User

jms_serializer:
   handlers:
       datetime:
           default_timezone: "UTC"

   metadata:
       cache: file
       debug: "%kernel.debug%"
       file_cache:
           dir: "%kernel.cache_dir%/serializer"
       auto_detection: true

       directories:
           FOSUB:
               namespace_prefix: "FOS\\UserBundle"
               path: "%kernel.root_dir%/serializer/FOSUB"

jms_security_extra:
  secure_all_services: false
  expressions: true

services:
    entvalley_user.registration_completed:
        class: Entvalley\UserBundle\EventListener\UserRegistrationCompletedListener
        arguments: ["@fos_user.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    entvalley.memcache:
        class: %doctrine.orm.cache.memcache_instance.class%
        calls:
            - [ connect, [ "127.0.0.1", "11212" ] ]
    entvalley.doctrine.memcache:
        class: %doctrine.orm.cache.memcache.class%
        calls:
            - [ setMemcache, [ @entvalley.memcache ] ]

    secdurity.acl.cache:
        class: "%security.acl.cache.doctrine.class%"
        arguments: [@entvalley.doctrine.memcache, @security.acl.permission_granting_strategy]

    security.access.owner_voter:
        class:      Entvalley\AppBundle\Security\Authorization\Voter\OwnerVoter
        arguments:  [@service_container, @security.acl.permission.map]
        public:     false
        tags:
            -       { name: security.voter }

    security.owner_evaluator:
        class: Entvalley\AppBundle\Security\OwnerEvaluator
        tags:
            - { name: security.expressions.function_evaluator, function: belongsTo, method: belongsTo }
    security.invited_to_evaluator:
        class: Entvalley\AppBundle\Security\InvitedToEvaluator
        arguments:  [@service_container]
        tags:
            - { name: security.expressions.function_evaluator, function: invitedTo, method: invitedTo }

exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
        Core.Encoding: 'UTF-8'
        Core.EscapeInvalidTags: true
        HTML.Allowed: 'a[href],b,i,u,li,ul,blockquote,ol,br,h1,h2,h3,img[src],span,div'