parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: tasks
    database_user: root
    database_password: nbuser
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: d1535f102c4487c5d029985bc7456d2e6
