parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: '5432'
    database_name: tasks
    database_user: postgres
    database_password: nbuser
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: d1535f102c4487c5d029985bc7456d2e6
