app_homepage:
    pattern:  /
    defaults: { _controller: entvalley.project_controller:indexAction }

app_task_view:
    pattern: /projects/{project}-{project_name}/tasks/{id}
    defaults: { _controller: entvalley.task_controller:viewAction }
    options:
        expose: true
    requirements:
        id: \d+
        project: \d+
        project_name: "[^/]+"

app_task_list:
    pattern:  /projects/{project}-{project_name}/tasks/{filterByType}
    defaults: { _controller: entvalley.task_controller:indexAction, filterByType: null }
    options:
        expose: true
    requirements:
        project: \d+
        project_name: "[^/]+"

app_task_edit:
    pattern: /projects/{project}-{project_name}/tasks/{id}/edit
    defaults: { _controller: entvalley.task_controller:editAction }
    options:
        expose: true
    requirements:
        id: \d+
        project: \d+
        project_name: "[^/]+"

app_task_delete:
    pattern:  /tasks/{id}/delete
    defaults: { _controller: entvalley.task_controller:deleteAction }
    requirements:
        id: \d+

app_comment_delete:
    pattern:  /comments/{id}/delete
    defaults: { _controller: entvalley.comment_controller:deleteAction }
    options:
        expose: true

app_comment_edit:
    pattern:  /comments/{id}/edit
    defaults: { _controller: entvalley.comment_controller:editAction }
    options:
        expose: true

app_command_list:
    pattern:  /commands
    defaults: { _controller: entvalley.command_controller:listAction }
    options:
        expose: true

app_command_send:
    pattern:  /commands/send
    defaults: { _controller: entvalley.command_controller:sendAction }

app_project_create:
    pattern:  /projects/create
    defaults: { _controller: entvalley.project_controller:createAction }

app_project_settings:
    pattern:  /projects/{project}-{project_name}/settings
    defaults: { _controller: entvalley.project_controller:settingsAction }
    options:
        expose: true
    requirements:
        project: \d+
        project_name: "[^/]+"

app_project_collaborators:
    pattern:  /projects/{project}-{project_name}/collaborators
    defaults: { _controller: entvalley.project_controller:collaboratorsAction }
    options:
        expose: true
    requirements:
        project: \d+
        project_name: "[^/]+"

app_project_collaborators_invite:
    pattern:  /projects/{project}-{project_name}/collaborators/invite
    defaults: { _controller: entvalley.project_controller:inviteCollaboratorsAction }
    options:
        expose: true
    requirements:
        project: \d+
        project_name: "[^/]+"

app_project_accept_invitation:
    pattern:  /projects/{project}-{project_name}/acceptInvitation
    defaults: { _controller: entvalley.project_controller:acceptInvitationAction }
    options:
        expose: true
    requirements:
        project: \d+
        project_name: "[^/]+"