Entvalley\AppBundle\Entity\Task:
    properties:
        comments:
            groups: [details]
        id:
            groups: [summary]
        title:
            groups: [summary]
        body:
            groups: [summary]
        safeBody:
            groups: [summary]
        author:
            groups: [summary]
        assignedTo:
            groups: [summary]
        createdAt:
            groups: [summary]
        lastModification:
            groups: [summary]
        project:
            groups: [summary]
        lastStatus:
            groups: [summary]
        status:
            groups: [summary]
        numberOfComments:
            groups: [summary]
        excerpt:
            groups: [summary]
            access_type: public_method
            accessor:
                getter: getExcerpt
                setter: setExcerpt
        htmlPurifier:
            exclude: true
    callback_methods:
        pre_serialize: [purifyHtmlTags]