Entvalley\AppBundle\Entity\Project:
    properties:
        id:
            groups: [summary]
        name:
            groups: [summary]
        canonicalName:
            groups: [summary]
        inprogressNumber:
            groups: [summary]
        unresolvedNumber:
            groups: [summary]
        totalNumber:
            groups: [summary]

    callback_methods:
        pre_serialize: [loadStats]