Entvalley\AppBundle\Entity\Comment:
    properties:
        id:
            groups: [details]
        text:
            groups: [details]
        safeText:
            groups: [details]
        author:
            groups: [details]
        createdAt:
            groups: [details]
        statusChange:
            groups: [details]
        task:
            exclude: true
        htmlPurifier:
            exclude: true
    callback_methods:
        pre_serialize: [purifyHtmlTags]