Entvalley\AppBundle\Entity\ProjectInvitation:
    exclusion_policy: ALL
    properties:
        id:
          expose: true
        invitedBy:
          expose: true
        invitedAt:
          expose: true
        isAccepted:
          expose: true
        inviteeEmail:
          expose: true